blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/OpenCML/Camel/blob/main/CODE_OF_CONDUCT.md
    about: Please read before participating in the community
  - name: Contributing Guide
    url: https://github.com/OpenCML/Camel/blob/main/CONTRIBUTING.md
    about: How to contribute to Camel
