[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "camel-lang"
version = "0.0.11"
description = "Camel: A Next-Generation Language for AI and High-Performance Computing"
keywords = ["language", "camel", "ai", "dsl", "graph", "opencml"]
authors = [{ name = "Zhenjie Wei", email = "kogler_s@outlook.com" }]
maintainers = [{ name = "Zhenjie Wei", email = "kogler_s@outlook.com" }]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Other",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Software Development :: Compilers",
    "Topic :: Software Development :: Interpreters",
]

[project.urls]
Homepage = "https://www.opencml.com"
Documentation = "https://docs.opencml.com"
Repository = "https://github.com/OpenCML/Camel"
Issues = "https://github.com/OpenCML/Camel/issues"

[project.scripts]
camel = "camel-lang.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["camel-lang"]